use my_db
--Грязное чтение READ UNCOMMITTED (2)

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION 
UPDATE EMPLOYEE
SET Phone = '88888888888' 
WHERE EMPLOYEE.employee_id = 3
ROLLBACK