use my_db

UPDATE EMPLOYEE
SET Phone = '86745687788' 
WHERE EMPLOYEE.employee_id = 3

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRANSACTION 
SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3
COMMIT
