use my_db
--Грязное чтение READ UNCOMMITTED (1)

UPDATE EMPLOYEE
SET Phone = '86745687788' 
WHERE EMPLOYEE.employee_id = 3

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRANSACTION 
SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3

SELECT * FROM EMPLOYEE
WHERE EMPLOYEE.employee_id = 3
COMMIT